/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData doc = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData down_open = const IconData(0xf004, fontFamily: _kFontFam);
  static const IconData circle = const IconData(0xf111, fontFamily: _kFontFam);
}
